import {CurrentPageProvider} from '@/store/CurrentProvider';
import {Menu} from '../../components/molecules/menu/Menu';
import './globals.css';
import {Inter} from 'next/font/google';
import ProviderReservation from '@/store/ProviderReservation';

const fonts = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '700', '800', '900']
});

export const metadata = {
  title: 'Hotels travelling',
  description: 'Generated by create next app'
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <ProviderReservation>
        <CurrentPageProvider>
          <body className={fonts.className}>
            <Menu />
            {children}
          </body>
        </CurrentPageProvider>
      </ProviderReservation>
    </html>
  );
}
